name: file_digest
description: Easily create digest hex for files
version: 0.0.2
homepage: https://github.com/DaPotatoMan/file_digest

topics:
  - file
  - digest

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  crypto: ">=3.0.3"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/worker.js
